spring.application.name=attendance-control
server.port=8080
app.base-url=http://localhost:8080
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima


spring.datasource.url=jdbc:postgresql://localhost:5432/db_attendance
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=8h
server.servlet.session.cookie.same-site=strict

logging.level.org.springframework=INFO
logging.level.com.elias.attendancecontrol=DEBUG

qr.duration-minutes=1
qr.default-width=300
qr.default-height=300

scheduler.qr-regeneration.fixed-rate.ms=60000
scheduler.activity-completion.cron=0 0 2 * * ?

session-token.duration-hours=2
security.max-sessions-per-user=1
security.session-prevents-login=false
security.bcrypt-strength=10

organization.plan.free.max-users=50
organization.plan.free.max-activities=10
organization.plan.basic.max-users=200
organization.plan.basic.max-activities=50
organization.plan.premium.max-users=1000
organization.plan.premium.max-activities=200