spring.application.name=attendace-control
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db_attendance
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=8h
server.servlet.session.cookie.same-site=strict

logging.level.org.springframework=INFO
logging.level.com.elias.attendancecontrol=DEBUG

app.base-url=http://localhost:8080

qr.duration-minutes=1
session-token.duration-hours=2
scheduler.qr-regeneration.fixed-rate.ms=60000

security.max-sessions-per-user=1
security.session-prevents-login=false
security.bcrypt-strength=10

organization.plan.free.max-users=50
organization.plan.free.max-activities=10
organization.plan.basic.max-users=200
organization.plan.basic.max-activities=50
organization.plan.premium.max-users=1000
organization.plan.premium.max-activities=200

scheduler.activity-completion.cron=0 0 2 * * ?

